services:
  nats:
    container_name: nats
    image: nats:latest
    command: -js --http_port 8222
    networks:
      - devsite

  web-test:
    container_name: web-test
    image: crccheck/hello-world
    networks:
      - devsite

  momus:
    container_name: momus
    image: rickdotnet/momus:latest
    environment:
      MS_NatsUrl: nats://nats:4222
    ports:
      - "80:8080"
    networks:
      - devsite

networks:
  devsite: